config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'users/new', to: 'users#new', as: :new_user
  post 'users', to: 'users#create'
  # get ‘conversations/index’
  resources :users
  resources :profiles
  resources :pets
  resources :breeds
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    elsif user.moderator?
      can [:create, :update, :delete], Profile, user_id: user.id
    elsif user.present?
      can :manage, User, id: user.id
    else
      can :read, Pet
    end
  end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  private
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :breed
  has_many :profiles, dependent: :destroy 
  has_many :users, through: :profiles
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :profiles, dependent: :destroy 
    has_many :pets, through: :profiles

    has_secure_password

    
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true

    enum role: [:normal, :moderator, :admin]

    after_initialize do
        if self.new_record?
          self.role ||= :normal 
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user
  
    # Define the current_user method:
    def current_user
      # Look up the current user based on user_id in the session cookie:
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
        redirect_to login_path, alert: 'You must be logged in to access this page. Please log in or sign up.' if current_user.nil?
    end

    rescue_from CanCan::AccessDenied do |exception|
        redirect_to user_path(@current_user), alert: "Access denied!"
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  # before_action :authenticate
  before_action :authorize

  def index
    @conversations = Conversation.where("sender_id = ? OR recipient_id = ?", current_user.id, current_user.id)
    @users = User.where.not(id: current_user.id)
  end

  def create
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    redirect_to conversation_messages_path(@conversation)
  end

  private
    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :authenticate
  before_action :authorize

  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end
  
  def index
    @messages = @conversation.messages

    @messages.where("user_id != ? AND read = ?", current_user.id, false).update_all(read: true)

    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    @message.user = current_user

    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private
    def message_params
      params.require(:message).permit(:content, :user_id)
    end
end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

    before_action :authorize, only: [:show]

    def index
        @pets_by_species = Pet.preload(:breed).group_by { |pet| pet.breed.species }
    end

    def show 
        @pet = Pet.find_by(id: params[:id])
    end

    def new
        @pet = Pet.new
    end 

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    before_action :authorize, only: [:index, :new, :edit]
    before_action :set_profile, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource

    def index
        @profiles = Profile.all
    end

    def show 
    end

    def new
        @profile = Profile.new
    end 
  
    def create
      @profile = Profile.new(profile_params)

      if @profile.valid?
        @profile.save
        redirect_to user_path(@profile.user_id)
      else 
        flash[:errors] = @user.errors.full_messages 
        redirect_to new_profile_path
      end 
    end 

    def edit
    end  

    def update
        @profile.update(profile_params)
        if @profile.valid?
            @profile.save
            redirect_to user_path(@profile.user_id)
        else
            flash[:errors] = @profile.errors.full_messages
            render :edit
        end
    end
  
    
    def destroy
        @profile.destroy
        redirect_to profiles_path
    end

  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_profile
        @profile = Profile.find_by(id: params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def profile_params
        params.require(:profile).permit(:pet_id, :user_id)
      end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    
    def create
        user = User.find_by(email: params[:login][:email].downcase)
        
        if user && user.authenticate(params[:login][:password]) 
          session[:user_id] = user.id.to_s
          redirect_to user_path(user), notice: 'Successfully logged in!'
        else
          flash.now.alert = "Incorrect email or password, try again."
          render :new
        end
    end
    
    def destroy
        session.delete(:user_id)
        redirect_to login_path, notice: "Logged out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :authorize, only: :index

    def index
        @users = User.all
    end

    def show 
        @user = User.find_by(id: params[:id])
        @profiles = @user.profiles
    end

    def new
        @user = User.new
    end 

    def create
        @user = User.new(user_params)
        @user.email.downcase!
        
        if @user.save
          flash[:notice] = "Account created successfully! Please log in."
          redirect_to root_path
        else
          flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid username, email and password and try again."
          render :new
        end
      end
    
    private
    
    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	
    <% if current_user %>
      <div id="nav"><%= "Logged in as #{current_user.username}" %> | <%= link_to 'Home', root_path %> | <%= link_to 'Account', user_path(current_user.id) %> | <%= link_to 'Log Out', logout_path, method: :delete %>
    <% else %>
      <%= link_to 'Home', root_path %> | <%= link_to 'Log In', login_path %> | <%= link_to 'Sign Up', new_user_path %>
    <% end %></div>
    <hr>

    <% if notice %>
    <%= notice %>
    <% end %>

    <% if alert %>
    <%= alert %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PetMe</title>
</head>
<body>
    <h1>PetMe</h1>
    <h2>Adopt the Perfect Pet for You</h2>
    <div class="center">
        <img src="https://www.theladders.com/wp-content/uploads/dog-cat-190709-1000x563.jpg" alt>
    </div>
    <h3><%= link_to "Find Your Next Best Friend", pets_path %></h3>

</body>
</html>

app/views/pets/index.html.erb
<h1>All Pets</h1> 

<% @pets_by_species.each do |species, pets| %>
<h3><%= species.pluralize %></h3>

<p style="text-align:center">
    <% pets.each do |pet| %><br>
        <%= link_to pet.name, pet_path(pet) %>
        <img class="center" style="max-width: 350px; max-height: 200px" src="<%= pet&.image %>" /><br>
    <% end %>
</p>
<% end %>

app/views/pets/show.html.erb
<h1>Pet Profile</h1>

<img class="center" style="max-width: 600px; max-height: 500px" src="<%= @pet.image %>" />
<h4><b> Name: </b><%= @pet.name %></h4>
<h4><b> Breed: </b><%= @pet.breed.name %></h4>
<h4><b> Age: </b><%= @pet.age %></h4>
<h4><b> Gender: </b><%= @pet.gender %></h4>
<h4><b> Size: </b><%= @pet.size %></h4>
<h4><b> Color: </b><%= @pet.color %></h4>
<h4><b> Good with Children: </b><%= @pet.good_with_children %></h4>
<h4><b> House Trained: </b><%= @pet.house_trained %></h4>
<h4><b> Special needs: </b><%= @pet.special_needs %></h4>
<h4><b> Personality: </b><%= @pet.temperament %></h4>

<h3><%= link_to "Back to All Pets", pets_path %></h3>

app/views/profiles/edit.html.erb
<% if flash[:errors] %>
    <h3>Errors: </h3>
        <ul>
            <% flash[:errors].each do |error| %>
             <li> <%= error %> </li>
            <% end %>
         </ul>
<% end %>

<%= form_with model: @profile do |f| %>
  <%= f.collection_select :pet_id, Pet.all, :id, :name %><br>
  <%= f.collection_select :user_id, User.all, :id, :username %><br>

<%= f.submit %>
<% end %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Pet Name</th>
      <th>Username</th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to profile.pet.name, pet_path(profile.pet.id) %></td>
        <td><%= link_to profile.user.username, user_path(profile.user.id) %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %> 

app/views/profiles/new.html.erb
<% if flash[:errors] %>
    <h3>Errors: </h3>
        <ul>
            <% flash[:errors].each do |error| %>
             <li> <%= error %> </li>
            <% end %>
         </ul>
<% end %>

<%= form_with model: @profile do |f| %>
  <%= f.collection_select :pet_id, Pet.all, :id, :name %><br>
  <%= f.collection_select :user_id, User.all, :id, :username %><br>

<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= "Welcome to PetMe, #{@user.username}!" %></h1>
<h2>Your Pets</h2>

<table>
  <thead>
    <tr>
      <th>Pet Name</th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= link_to profile.pet.name, pet_path %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "Add Pets", new_profile_path %></p> 
<p><%= link_to "Visit All Profiles", profiles_path %></p>
<p><%= link_to "View Your Messages", conversations_path %></p>